version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    default_reviewers:
      - nrkno/linuxadmin
    update_schedule: daily
    allowed_updates:
      - match:
          update_type: security

  - package_manager: "docker"
    directory: "/"
    default_reviewers:
      - nrkno/linuxadmin
    update_schedule: daily
    allowed_updates:
      - match:
          update_type: security
